AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  LayerAWSCLI:
    Type: String
  NotificationEmail:
    Type: String
Resources:
  Alarm:
    Properties:
      AlarmActions:
      - Ref: AlarmTopic
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
      - Name: FunctionName
        Value:
          Ref: GitBackup
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: '1'
    Type: AWS::CloudWatch::Alarm
  AlarmTopic:
    Properties:
      Subscription:
      - Endpoint:
          Ref: NotificationEmail
        Protocol: email
    Type: AWS::SNS::Topic
  GitBackup:
    Properties:
      CodeUri: s3://mjs-personal-s3/cbc2c49600dd90bd970fc19c4dbd1f62
      Events:
        GitBackupScheduledEvent:
          Properties:
            Schedule: cron(0 18 ? * FRI *)
          Type: Schedule
      FunctionName: git-backup
      Handler: handler.run
      Layers:
      - arn:aws:lambda:ap-southeast-2:553035198032:layer:git:5
      - Ref: LayerAWSCLI
      MemorySize: 1024
      Policies:
      - AWSCodeCommitPowerUser
      Runtime: python3.7
      Timeout: 300
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
